name: ReverseText
description: >
    A demonstration of the PureMVC Framework for Dart.
    This simple demo shows the most common actors and collaborations
    found in a PureMVC application. A form allows you to enter text,
    click a button and have the text reversed and displayed in another
    text box. A check box allows you to have your text reversed continuously
    as you type. Finally, when the text in the input box is the same as the
    text after reversal, the output text box's label changes to indicate that
    a palindrome was detected.

version: 2.0.2
author: Cliff Hall <cliff.hall@puremvc.org>
homepage: http://www.puremvc.org
dependencies:
  puremvc: any